import Head from 'next/head'
import Header from './Components/Header'
import Sidebar from './Components/Sidebar'

export default function Home() {
  return (
    <div >
      <Head>
        <title>FaceBook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='flex bg-gray-100' >
        {/* Leftsidebar */}
      <Sidebar />
      {/* feed(creat post and posts) */}
      {/* Rightsidebar */}
      </main>
    </div>
  )
}
